# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    build: .
    environment:
      PAGERDUTY_API_KEY:
      DATABASE_URL:
    command: bundle exec /app/bin/pd2pg
    volumes:
      - .:/app
