# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    build: .
    environment:
      PAGERDUTY_API_KEY: RxaM6KGEGdMjmWJCMide
      DATABASE_URL: postgres://postgres:ffs@scratch3.central.prd.useast1.3dna.io:5432/pagerduty
    command: bundle exec /app/reporter.rb 
    volumes:
      - .:/app
